name: cleo
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - absl-py=2.1.0
  - accelerate=0.21.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - antlr-python-runtime=4.9.3
  - anyio=3.7.1
  - aom=3.8.2
  - archspec=0.2.3
  - arrow=1.3.0
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - autogluon=1.0.0
  - autogluon.common=1.0.0
  - autogluon.core=1.0.0
  - autogluon.features=1.0.0
  - autogluon.multimodal=1.0.0
  - autogluon.tabular=1.0.0
  - autogluon.timeseries=1.0.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - blessed=1.19.1
  - blosc=1.21.5
  - boltons=23.1.1
  - boto3=1.34.71
  - botocore=1.34.71
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.27.0
  - c-blosc2=2.13.2
  - ca-certificates=2024.2.2
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cairo=1.18.0
  - catalogue=2.0.10
  - catboost=1.2.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=5.2.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - cleo=2.1.0
  - click=8.1.7
  - cloudpathlib=0.16.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - conda=24.3.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - confection=0.1.4
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - crashtest=0.4.1
  - croniter=1.3.15
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - cytoolz=0.12.3
  - dask-core=2024.3.1
  - dataclasses=0.8
  - datasets=2.18.0
  - dateutils=0.6.12
  - dav1d=1.2.1
  - deepdiff=6.7.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distlib=0.3.8
  - distro=1.9.0
  - dulwich=0.21.7
  - evaluate=0.4.1
  - exceptiongroup=1.2.0
  - expat=2.6.2
  - fastai=2.7.14
  - fastapi=0.110.0
  - fastcore=1.5.29
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - filelock=3.13.3
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2023.12.2
  - gdk-pixbuf=2.42.10
  - gdown=5.1.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - gluonts=0.14.4
  - gmp=6.3.0
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - graphviz=9.0.0
  - grpcio=1.59.3
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - harfbuzz=8.3.0
  - huggingface_hub=0.22.1
  - icu=73.2
  - idna=3.6
  - imagecodecs=2024.1.1
  - imageio=2.34.0
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - inquirer=3.1.4
  - itsdangerous=2.1.2
  - jaraco.classes=3.3.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.17.3
  - jxrlib=1.1
  - keyring=24.3.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - langcodes=3.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libhwy=1.0.7
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libparquet=15.0.0
  - libpng=1.6.43
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - librsvg=2.56.3
  - libsentencepiece=0.1.99
  - libsolv=0.7.28
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=1.7.6
  - libxml2=2.12.6
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightgbm=4.1.0
  - lightning-utilities=0.11.1
  - llvm-openmp=18.1.2
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - mdurl=0.1.2
  - menuinst=2.0.2
  - mlforecast=0.10.0
  - model-index=0.1.11
  - more-itertools=10.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - murmurhash=1.0.10
  - ncurses=6.4.20240210
  - networkx=3.2.1
  - nlpaug=1.1.11
  - nltk=3.8.1
  - nomkl=1.0
  - nptyping=2.4.1
  - numba=0.59.1
  - numpy=1.26.4
  - omegaconf=2.3.0
  - openjpeg=2.5.2
  - openmim=0.3.7
  - openssl=3.2.1
  - orc=1.9.2
  - ordered-set=4.1.0
  - orjson=3.9.15
  - pandas=2.1.4
  - pango=1.52.1
  - partd=1.4.1
  - pathy=0.10.2
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.4
  - pkginfo=1.10.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - plotly=5.19.0
  - pluggy=1.4.0
  - poetry=1.8.2
  - poetry-core=1.9.0
  - poetry-plugin-export=1.7.1
  - preshed=3.0.9
  - protobuf=4.24.4
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py-xgboost=1.7.6
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.6.4
  - pydantic-core=2.16.3
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyparsing=3.1.2
  - pyproject_hooks=1.0.0
  - pyrsistent=0.20.0
  - pysocks=1.7.1
  - pytesseract=0.3.10
  - python=3.10.14
  - python-build=1.1.1
  - python-dateutil=2.9.0
  - python-editor=1.0.4
  - python-fastjsonschema=2.19.1
  - python-graphviz=0.20.3
  - python-installer=0.7.0
  - python-multipart=0.0.9
  - python-slugify=8.0.4
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-lightning=2.0.9
  - pytorch-metric-learning=1.7.3
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - rapidfuzz=3.7.0
  - rav1e=0.6.6
  - re2=2023.09.01
  - readchar=4.0.5
  - readline=8.2
  - regex=2023.12.25
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - responses=0.18.0
  - rich=13.7.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s3transfer=0.10.1
  - sacremoses=0.0.53
  - safetensors=0.4.2
  - scikit-image=0.19.3
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - sentencepiece=0.1.99
  - sentencepiece-python=0.1.99
  - sentencepiece-spm=0.1.99
  - seqeval=1.2.2
  - setuptools=69.2.0
  - shellingham=1.5.4
  - six=1.16.0
  - sleef=3.5.1
  - smart_open=5.2.1
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.4.8
  - starlette=0.36.3
  - starsessions=1.3.0
  - statsforecast=1.4.0
  - statsmodels=0.14.1
  - svt-av1=2.0.0
  - sympy=1.12
  - tabulate=0.9.0
  - tenacity=8.2.3
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - text-unidecode=1.3
  - thinc=8.2.2
  - threadpoolctl=3.4.0
  - tifffile=2024.2.12
  - timm=0.9.16
  - tk=8.6.13
  - tokenizers=0.13.3
  - tomli=2.0.1
  - tomlkit=0.12.4
  - toolz=0.12.1
  - torchmetrics=1.1.2
  - torchvision=0.15.2
  - tqdm=4.66.2
  - traitlets=5.14.2
  - transformers=4.31.0
  - trove-classifiers=2024.3.25
  - truststore=0.8.0
  - typer=0.9.4
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - typish=1.9.3
  - tzdata=2024a
  - ujson=5.9.0
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - utilsforecast=0.1.2
  - uvicorn=0.29.0
  - virtualenv=20.25.1
  - wasabi=1.1.2
  - wcwidth=0.2.13
  - weasel=0.3.4
  - websocket-client=1.7.0
  - websockets=11.0.3
  - werkzeug=3.0.1
  - wheel=0.43.0
  - window-ops=0.0.15
  - xattr=1.1.0
  - xgboost=1.7.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.9.4
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - altair==5.2.0
      - backoff==2.2.1
      - blinker==1.7.0
      - cachetools==5.3.3
      - docstring-parser==0.16
      - gitdb==4.0.11
      - gitpython==3.1.42
      - jsonargparse==4.27.7
      - lightning==2.2.1
      - lightning-cloud==0.5.64
      - packaging==23.2
      - pydeck==0.8.1b0
      - pynndescent==0.5.11
      - rdkit==2023.9.5
      - smmap==5.0.1
      - streamlit==1.32.2
      - streamlit-ace==0.1.1
      - toml==0.10.2
      - tornado==6.4
      - typeshed-client==2.5.1
      - umap-learn==0.5.5
